import numpy as np
#ufuncs是通用函数的缩写，它是一种对ndarray对象执行操作的numpy函数
#ufuncs实现矢量化（将迭代语句转化为基于矢量的操作）操作，它们在数组上执行元素级运算
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
#加法
newarr=np.add(arr1,arr2)
print(newarr)
#减法
newarr=np.subtract(arr1,arr2)
print(newarr)
#乘法
newarr=np.multiply(arr1,arr2)
print(newarr)
#除法
newarr=np.divide(arr1,arr2)
print(newarr)
#幂运算
newarr=np.power(arr1,arr2)
print(newarr)
#取余
newarr=np.mod(arr1,arr2)
print(newarr)
#求商和余数
newarr=np.divmod(arr1,arr2)
print(newarr)
#绝对值
newarr=np.absolute(arr1)
print(newarr)
#四舍五入
arr3=np.array([0.1,0.2,0.5,0.6,0.7])
newarr=np.around(arr3)
print(newarr)
#向上取整
newarr=np.ceil(arr3)
print(newarr)
#向下取整
newarr=np.floor(arr3)
print(newarr)
#对数（log表示以e为底数）
arr4=np.array([1,2,3,4])
newarr=np.log2(arr4)
print(newarr)
#三角函数
arr4=np.array([0,30,45,60,90])
newarr=np.sin(arr4*np.pi/180)
print(newarr)
newarr=np.cos(arr4*np.pi/180)
print(newarr)
newarr=np.tan(arr4*np.pi/180)
print(newarr)
#反三角函数
arr5=np.array([0.1,0.2,0.5])
newarr=np.arcsin(arr5)
print(newarr)
newarr=np.arccos(arr5)
print(newarr)
newarr=np.arctan(arr5)
print(newarr)